version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
      - loki

  mimir:
    image: grafana/mimir:latest
    ports:
      - "9009:9009"
    command:
      - '-config.file=/etc/mimir/config.yaml'
    volumes:
      - ./config/mimir-config.yaml:/etc/mimir/config.yaml
    depends_on:
      - loki

volumes:
  prometheus_data:
