# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tac.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttac.proto\x12\ttelemetry\"\'\n\tTimeRange\x12\r\n\x05start\x18\x01 \x01(\t\x12\x0b\n\x03\x65nd\x18\x02 \x01(\t\"o\n\x0cMetricsQuery\x12\x0e\n\x06metric\x18\x01 \x01(\t\x12(\n\ntime_range\x18\x02 \x01(\x0b\x32\x14.telemetry.TimeRange\x12\x13\n\x0b\x61ggregation\x18\x03 \x01(\t\x12\x10\n\x08interval\x18\x04 \x01(\t\"D\n\tLogsQuery\x12\r\n\x05query\x18\x01 \x01(\t\x12(\n\ntime_range\x18\x02 \x01(\x0b\x32\x14.telemetry.TimeRange\"4\n\x0f\x44\x61shboardConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"<\n\rQueryResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tac_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TIMERANGE']._serialized_start=24
  _globals['_TIMERANGE']._serialized_end=63
  _globals['_METRICSQUERY']._serialized_start=65
  _globals['_METRICSQUERY']._serialized_end=176
  _globals['_LOGSQUERY']._serialized_start=178
  _globals['_LOGSQUERY']._serialized_end=246
  _globals['_DASHBOARDCONFIG']._serialized_start=248
  _globals['_DASHBOARDCONFIG']._serialized_end=300
  _globals['_QUERYRESPONSE']._serialized_start=302
  _globals['_QUERYRESPONSE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
