apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.0.0
        ports:
        - containerPort: 3100
        args:
          - -config.file=/etc/loki/local-config.yaml
        volumeMounts:
        - name: loki-config-volume
          mountPath: /etc/loki/
volumes:
- name: loki-config-volume
  configMap:
    name: loki-config

---
apiVersion: v1
kind: Service
metadata:
  name: loki-service
spec:
  selector:
    app: loki
  ports:
  - protocol: TCP
    port: 3100
    targetPort: 3100
  type: LoadBalancer
