apiVersion: apps/v1
kind: Deployment
metadata:
  name: tac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tac
  template:
    metadata:
      labels:
        app: tac
    spec:
      containers:
      - name: tac
        image: tac:latest
        imagePullPolicy: Never  # Use 'Never' if you're sure the image is already present on all nodes
        ports:
        - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: tac
spec:
  selector:
    app: tac
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
