# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tac_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tac_pb2 as tac__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11tac_service.proto\x12\ttelemetry\x1a\ttac.proto\x1a\x1bgoogle/protobuf/empty.proto2\xea\x03\n\nTacService\x12\x43\n\x0e\x43ollectMetrics\x12\x17.telemetry.MetricsQuery\x1a\x18.telemetry.QueryResponse\x12\x41\n\x0cQueryMetrics\x12\x17.telemetry.MetricsQuery\x1a\x18.telemetry.QueryResponse\x12=\n\x0b\x43ollectLogs\x12\x14.telemetry.LogsQuery\x1a\x18.telemetry.QueryResponse\x12;\n\tQueryLogs\x12\x14.telemetry.LogsQuery\x1a\x18.telemetry.QueryResponse\x12G\n\x0f\x43reateDashboard\x12\x1a.telemetry.DashboardConfig\x1a\x18.telemetry.QueryResponse\x12G\n\x0fUpdateDashboard\x12\x1a.telemetry.DashboardConfig\x1a\x18.telemetry.QueryResponse\x12\x46\n\x0eListDashboards\x12\x16.google.protobuf.Empty\x1a\x1a.telemetry.DashboardConfig0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tac_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TACSERVICE']._serialized_start=73
  _globals['_TACSERVICE']._serialized_end=563
# @@protoc_insertion_point(module_scope)
